# Gameplay settings
GAME_SPEED = 500
NEXT_LEVEL_SLEEP = 5

# Player setting
PLAYER_SPEED = 15
PLAYER_LASER_SPEED = 10
PLAYER_LASER_COOLDOWN = 50    # ms

# Enemy settings
ENEMY_SPEED = 7
ENEMY_MOVE_SLEEP = 0.1
ENEMY_LASER_SPEED = 10
ENEMY_SHOOT_TIMER = 2000        # ms
ENEMY_FALL_TIMER = 3000            # ms
ENEMY_FALLING_SPEED = 10

# Next level setting (difficulty)
NEXTLVL_SHOOT_TIMER = 200      # ms
NEXTLVL_ENEMY_LASER_SPEED = 2

# Board settings
BOARD_WIDTH = 800
BOARD_HEIGHT = 600
IMAGE_WIDTH = 50
IMAGE_HEIGHT = 50
