GAME_SPEED = 1
ENEMY_SPEED = 500

BOARD_WIDTH = 20
BOARD_HEIGHT = 13

TILE_WIDTH = 45
TILE_HEIGHT = 45

TILE_BACKGROUND = 0
TILE_PLAYER = 1
TILE_ENEMY = 2
TILE_PLAYERLASER = 3
TILE_ENEMYLASER = 4
TILE_LIVES = 5
TILE_ZEROLIVES = 6
TILE_ONELIFE = 7
TILE_TWOLIVES = 8
TILE_THREELIVES = 9
